import { useState, useEffect } from 'react'

import Card from 'library/components/Card'
import FormField from 'library/components/FormField'
import ColorfulSpinner from 'library/components/ColorfulSpinner'

import Info from 'library/components/Info'

import { ContainerProps } from './HomeContainer'

import styles from './home.module.scss'

const TITLE = 'The Community Showcase'
const SUB_TITLE = 'Browse through a collection of imaginative and visually stunning images generated by DALL-E AI'

// interface IRenderCards {
// 	data: any,
// 	title: string
// }

// const RenderCards = ({
// 	data,
// 	title,
// }: IRenderCards) => {
// 	if (data?.length > 0) return data.map((post: any) => <Card key={post._id} {...post} />)

// 	return <h2>{title}</h2>
// }

const Home = ({
}: ContainerProps) => {
	const [isLoading, setIsLoading] = useState(false)
	const [allPosts, setAllPosts] = useState<null | any[]>(null)

	return (
		<div className={styles.wrapper}>
			<Info
				title={TITLE}
				subTitle={SUB_TITLE}
			/>
			{/* <FormField /> */}

			<div>
				{isLoading ? (
					<div className={styles.loaderWrapper}>
						<ColorfulSpinner size={4} /> 
					</div>
				) : <div>not loading</div>}
			</div>
		</div>
	)
}

export default Home